backend:
  name: git-gateway
  branch: main

media_folder: "/"
public_folder: "/"

collections:
  - name: "categories"
    label: "Усі розділи сайту"
    folder: "content/categories" # Папка, де будуть лежати твої розділи
    create: true # Дозволяє додавати НОВІ категорії
    slug: "{{title}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Назва розділу (напр. Музика KohaN)", name: "title", widget: "string"}
      - {label: "Порядковий номер (1, 2, 3...)", name: "order", widget: "number", default: 10}
      - label: "Тип розділу"
        name: "type"
        widget: "select"
        options: 
          - {label: "Список з іконками (Соцмережі)", value: "socials"}
          - {label: "Список з обкладинками (Музика)", value: "music"}
          - {label: "Окреме відео", value: "video"}
      - label: "Вміст розділу"
        name: "items"
        widget: "list"
        fields:
          - {label: "Назва елемента", name: "item_title", widget: "string"}
          - {label: "Посилання", name: "item_link", widget: "string"}
          - {label: "Картинка (для музики)", name: "item_image", widget: "image", required: false}
