backend:
  name: git-gateway
  branch: main

media_folder: "/"
public_folder: "/"

collections:
  - name: "database"
    label: "База даних сайту"
    files:
      - label: "Керування контентом"
        name: "links"
        file: "data.json"
        fields:
          - label: "Всі розділи сайту"
            name: "sections"
            widget: "list"
            summary: "{{title}}"
            types:
              - label: "🎵 Секція Музики"
                name: "music_section"
                widget: "object"
                fields:
                  - {label: "Заголовок розділу", name: "title", widget: "string"}
                  - label: "Список треків"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Назва треку", name: "item_title", widget: "string"}
                      - {label: "Посилання", name: "item_link", widget: "string"}
                      - {label: "Обкладинка", name: "item_image", widget: "image", required: false}

              - label: "📱 Секція Соцмереж"
                name: "social_section"
                widget: "object"
                fields:
                  - {label: "Заголовок розділу", name: "title", widget: "string"}
                  - {label: "Аватарка автора (необов'язково)", name: "avatar", widget: "image", required: false}
                  - label: "Список посилань"
                    name: "items"
                    widget: "list"
                    fields:
                      - {label: "Назва", name: "item_title", widget: "string"}
                      - {label: "Посилання", name: "item_link", widget: "string"}

              - label: "💥 Окрема кнопка (Відео/Плейлист)"
                name: "video_button"
                widget: "object"
                fields:
                  - {label: "Текст на кнопці", name: "title", widget: "string"}
                  - {label: "Посилання", name: "item_link", widget: "string"}
                  - {label: "Тип іконки", name: "icon_type", widget: "select", options: ["youtube", "play", "users"]}
